"""
Phase 1 material expansion — ~40 specific alloy grades and engineering materials.
Sources:
  - ASM Handbooks Vol 1 (Steels), Vol 2 (Nonferrous)
  - ASTM standards (property ranges for spec grades)
  - Bath ICE v3.0 (embodied energy / CO₂)
  - Ashby App A (6th ed., 2025) for eco cross-check

Run from repo root:
    python scripts/add_phase1_materials.py
"""

import json
import os
from pathlib import Path

REPO = Path(__file__).parent.parent
DATA_DIR = REPO / "data"
MAT_DIR = DATA_DIR / "materials"

# ---------------------------------------------------------------------------
# New material definitions
# ---------------------------------------------------------------------------
NEW_MATERIALS = [

    # ── Aluminum alloys ────────────────────────────────────────────────────
    {
        "id": "aluminum-1100",
        "name": "Aluminum 1100 (commercially pure)",
        "family": "metals",
        "short_name": "Al 1100",
        "subfamily": "aluminum-alloys",
        "applications": ["Food packaging", "Chemical equipment", "Heat exchangers", "Decorative trim"],
        "properties": {
            "density_kg_m3":              {"min": 2710, "max": 2720, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 2.0,  "max": 2.5,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 69,   "max": 70,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 97,   "max": 125,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 110,  "max": 130,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 35, "max": 45,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.09, "max": 0.15, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 643,  "max": 657,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 904,  "max": 920,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 218,  "max": 222,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 23.6, "max": 23.6, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 2.9, "max": 3.1, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 155,  "max": 200,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 8.1,  "max": 11.5, "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 11,   "max": 17,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 1.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "aluminum-2024-t3",
        "name": "Aluminum 2024-T3",
        "family": "metals",
        "short_name": "Al 2024-T3",
        "subfamily": "aluminum-alloys",
        "applications": ["Aircraft fuselage skins", "Wing structures", "Rivet stock", "Aerospace fittings"],
        "notes": "Cu-Mg alloy; T3 = solution treated + cold worked. High fatigue resistance.",
        "properties": {
            "density_kg_m3":              {"min": 2770, "max": 2790, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 3.5,  "max": 5.0,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 73,   "max": 74,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 345,  "max": 380,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 483,  "max": 510,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 26, "max": 37,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.12, "max": 0.18, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 502,  "max": 638,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 875,  "max": 900,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 120,  "max": 135,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 23.2, "max": 23.2, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 5.6, "max": 6.1, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 155,  "max": 210,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 9.0,  "max": 12.5, "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.40, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 11,   "max": 17,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 1.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "aluminum-6061-t6",
        "name": "Aluminum 6061-T6",
        "family": "metals",
        "short_name": "Al 6061-T6",
        "subfamily": "aluminum-alloys",
        "applications": ["Structural frames", "Bicycle frames", "Marine fittings", "Automotive parts", "Machined components"],
        "notes": "Most widely used structural Al alloy. Mg-Si alloy; T6 = solution treated + peak aged.",
        "properties": {
            "density_kg_m3":              {"min": 2700, "max": 2710, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 2.4,  "max": 3.2,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 68,   "max": 70,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 276,  "max": 310,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 310,  "max": 330,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 29, "max": 35,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.08, "max": 0.12, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 582,  "max": 652,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 896,  "max": 900,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 160,  "max": 170,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 23.4, "max": 23.6, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 3.7, "max": 4.1, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 155,  "max": 200,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 8.1,  "max": 12.0, "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 11,   "max": 17,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 1.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "aluminum-7075-t6",
        "name": "Aluminum 7075-T6",
        "family": "metals",
        "short_name": "Al 7075-T6",
        "subfamily": "aluminum-alloys",
        "applications": ["Airframe spars", "Gears and shafts", "Missile components", "Bicycle frames (high-end)"],
        "notes": "Zn-Mg-Cu alloy; highest-strength common Al alloy. Lower toughness than 2024.",
        "properties": {
            "density_kg_m3":              {"min": 2800, "max": 2820, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 4.0,  "max": 5.5,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 71,   "max": 72,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 503,  "max": 530,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 572,  "max": 590,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 22, "max": 29,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.08, "max": 0.11, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 477,  "max": 635,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 955,  "max": 965,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 130,  "max": 145,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 23.4, "max": 23.6, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 5.1, "max": 5.4, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 155,  "max": 210,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 9.0,  "max": 13.0, "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.40, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 11,   "max": 17,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 1.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "aluminum-5052-h32",
        "name": "Aluminum 5052-H32",
        "family": "metals",
        "short_name": "Al 5052-H32",
        "subfamily": "aluminum-alloys",
        "applications": ["Marine hull plating", "Fuel tanks", "Pressure vessels", "Sheet metal work"],
        "notes": "Mg alloy; excellent corrosion resistance. H32 = strain hardened + stabilized.",
        "properties": {
            "density_kg_m3":              {"min": 2680, "max": 2690, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 2.8,  "max": 3.5,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 70,   "max": 71,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 193,  "max": 207,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 228,  "max": 262,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 25, "max": 35,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.12, "max": 0.17, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 607,  "max": 649,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 880,  "max": 900,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 134,  "max": 142,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 23.6, "max": 23.8, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 4.9, "max": 5.1, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 155,  "max": 200,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 8.1,  "max": 11.5, "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 11,   "max": 17,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 1.0,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Stainless steels ───────────────────────────────────────────────────
    {
        "id": "stainless-304",
        "name": "Stainless steel 304 (18-8)",
        "family": "metals",
        "short_name": "SS 304",
        "subfamily": "ferrous-metals",
        "applications": ["Food processing equipment", "Kitchen appliances", "Chemical tanks", "Architectural panels"],
        "notes": "Most common austenitic SS. 18% Cr, 8% Ni. Annealed condition.",
        "properties": {
            "density_kg_m3":              {"min": 7900, "max": 8000, "source": "ASM Handbook Vol 1"},
            "price_USD_kg":               {"min": 3.0,  "max": 4.5,  "source": "ASM Handbook Vol 1"},
            "youngs_modulus_GPa":         {"min": 193,  "max": 200,  "source": "ASM Handbook Vol 1"},
            "yield_strength_MPa":         {"min": 170,  "max": 310,  "source": "ASM Handbook Vol 1"},
            "ultimate_strength_MPa":      {"min": 480,  "max": 650,  "source": "ASM Handbook Vol 1"},
            "fracture_toughness_MPa_sqrt_m": {"min": 100, "max": 200, "source": "ASM Handbook Vol 1"},
            "elongation":                 {"min": 0.40, "max": 0.55, "source": "ASM Handbook Vol 1"},
            "melting_point_C":            {"min": 1400, "max": 1450, "source": "ASM Handbook Vol 1"},
            "specific_heat_J_kgK":        {"min": 500,  "max": 510,  "source": "ASM Handbook Vol 1"},
            "thermal_conductivity_W_mK":  {"min": 16.2, "max": 16.3, "source": "ASM Handbook Vol 1"},
            "thermal_expansion_uK":       {"min": 17.2, "max": 17.8, "source": "ASM Handbook Vol 1"},
            "electrical_resistivity_uohm_cm": {"min": 72, "max": 74, "source": "ASM Handbook Vol 1"},
            "embodied_energy_MJ_kg":      {"min": 50,   "max": 60,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 5.5,  "max": 6.8,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.65, "max": 0.80, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 10,   "max": 18,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.7,  "max": 1.2,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "stainless-316l",
        "name": "Stainless steel 316L",
        "family": "metals",
        "short_name": "SS 316L",
        "subfamily": "ferrous-metals",
        "applications": ["Marine hardware", "Surgical implants", "Chemical processing", "Pharmaceutical equipment"],
        "notes": "Mo-bearing austenitic SS; superior pitting/crevice corrosion resistance. Low-C grade prevents sensitization.",
        "properties": {
            "density_kg_m3":              {"min": 7980, "max": 8010, "source": "ASM Handbook Vol 1"},
            "price_USD_kg":               {"min": 3.5,  "max": 5.0,  "source": "ASM Handbook Vol 1"},
            "youngs_modulus_GPa":         {"min": 193,  "max": 200,  "source": "ASM Handbook Vol 1"},
            "yield_strength_MPa":         {"min": 170,  "max": 310,  "source": "ASM Handbook Vol 1"},
            "ultimate_strength_MPa":      {"min": 485,  "max": 620,  "source": "ASM Handbook Vol 1"},
            "fracture_toughness_MPa_sqrt_m": {"min": 100, "max": 200, "source": "ASM Handbook Vol 1"},
            "elongation":                 {"min": 0.35, "max": 0.50, "source": "ASM Handbook Vol 1"},
            "melting_point_C":            {"min": 1370, "max": 1400, "source": "ASM Handbook Vol 1"},
            "specific_heat_J_kgK":        {"min": 500,  "max": 510,  "source": "ASM Handbook Vol 1"},
            "thermal_conductivity_W_mK":  {"min": 16.0, "max": 16.5, "source": "ASM Handbook Vol 1"},
            "thermal_expansion_uK":       {"min": 16.0, "max": 16.5, "source": "ASM Handbook Vol 1"},
            "electrical_resistivity_uohm_cm": {"min": 73, "max": 75, "source": "ASM Handbook Vol 1"},
            "embodied_energy_MJ_kg":      {"min": 55,   "max": 65,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 6.1,  "max": 7.2,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.65, "max": 0.80, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 10,   "max": 18,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.7,  "max": 1.2,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "stainless-17-4ph",
        "name": "Stainless steel 17-4 PH (H900)",
        "family": "metals",
        "short_name": "SS 17-4PH",
        "subfamily": "ferrous-metals",
        "applications": ["Aerospace components", "Oil and gas valves", "Nuclear reactors", "Pump shafts"],
        "notes": "Precipitation-hardened martensitic SS. H900 condition (aged at 900°F / 482°C) = peak strength.",
        "properties": {
            "density_kg_m3":              {"min": 7780, "max": 7800, "source": "ASM Handbook Vol 1"},
            "price_USD_kg":               {"min": 8.0,  "max": 15.0, "source": "ASM Handbook Vol 1"},
            "youngs_modulus_GPa":         {"min": 196,  "max": 200,  "source": "ASM Handbook Vol 1"},
            "yield_strength_MPa":         {"min": 1170, "max": 1310, "source": "ASM Handbook Vol 1"},
            "ultimate_strength_MPa":      {"min": 1310, "max": 1380, "source": "ASM Handbook Vol 1"},
            "fracture_toughness_MPa_sqrt_m": {"min": 55, "max": 77,  "source": "ASM Handbook Vol 1"},
            "elongation":                 {"min": 0.05, "max": 0.10, "source": "ASM Handbook Vol 1"},
            "melting_point_C":            {"min": 1400, "max": 1440, "source": "ASM Handbook Vol 1"},
            "specific_heat_J_kgK":        {"min": 460,  "max": 480,  "source": "ASM Handbook Vol 1"},
            "thermal_conductivity_W_mK":  {"min": 17.8, "max": 18.4, "source": "ASM Handbook Vol 1"},
            "thermal_expansion_uK":       {"min": 10.8, "max": 11.2, "source": "ASM Handbook Vol 1"},
            "electrical_resistivity_uohm_cm": {"min": 77, "max": 80, "source": "ASM Handbook Vol 1"},
            "embodied_energy_MJ_kg":      {"min": 55,   "max": 70,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 6.0,  "max": 7.5,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.60, "max": 0.75, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 10,   "max": 18,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.7,  "max": 1.2,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "steel-4140",
        "name": "Alloy steel 4140 (Q&T)",
        "family": "metals",
        "short_name": "4140 steel",
        "subfamily": "ferrous-metals",
        "applications": ["Gears and shafts", "Die casting dies", "Drilling equipment", "Connecting rods"],
        "notes": "Cr-Mo low-alloy steel, quenched & tempered at 315°C. Good toughness-to-strength balance.",
        "properties": {
            "density_kg_m3":              {"min": 7850, "max": 7870, "source": "ASM Handbook Vol 1"},
            "price_USD_kg":               {"min": 1.5,  "max": 2.0,  "source": "ASM Handbook Vol 1"},
            "youngs_modulus_GPa":         {"min": 200,  "max": 210,  "source": "ASM Handbook Vol 1"},
            "yield_strength_MPa":         {"min": 655,  "max": 980,  "source": "ASM Handbook Vol 1"},
            "ultimate_strength_MPa":      {"min": 690,  "max": 1030, "source": "ASM Handbook Vol 1"},
            "fracture_toughness_MPa_sqrt_m": {"min": 50, "max": 80,  "source": "ASM Handbook Vol 1"},
            "elongation":                 {"min": 0.12, "max": 0.18, "source": "ASM Handbook Vol 1"},
            "melting_point_C":            {"min": 1427, "max": 1510, "source": "ASM Handbook Vol 1"},
            "specific_heat_J_kgK":        {"min": 460,  "max": 480,  "source": "ASM Handbook Vol 1"},
            "thermal_conductivity_W_mK":  {"min": 42,   "max": 48,   "source": "ASM Handbook Vol 1"},
            "thermal_expansion_uK":       {"min": 12.3, "max": 13.0, "source": "ASM Handbook Vol 1"},
            "electrical_resistivity_uohm_cm": {"min": 22, "max": 25, "source": "ASM Handbook Vol 1"},
            "embodied_energy_MJ_kg":      {"min": 32,   "max": 38,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 2.4,  "max": 2.9,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.40, "max": 0.55, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 8,    "max": 12,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 0.9,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "steel-4340",
        "name": "Alloy steel 4340 (Q&T)",
        "family": "metals",
        "short_name": "4340 steel",
        "subfamily": "ferrous-metals",
        "applications": ["Aircraft landing gear", "Crankshafts", "Ordnance", "High-strength bolts"],
        "notes": "Ni-Cr-Mo steel, high hardenability. Among the highest-strength structural steels.",
        "properties": {
            "density_kg_m3":              {"min": 7850, "max": 7870, "source": "ASM Handbook Vol 1"},
            "price_USD_kg":               {"min": 2.0,  "max": 2.5,  "source": "ASM Handbook Vol 1"},
            "youngs_modulus_GPa":         {"min": 200,  "max": 210,  "source": "ASM Handbook Vol 1"},
            "yield_strength_MPa":         {"min": 800,  "max": 1470, "source": "ASM Handbook Vol 1"},
            "ultimate_strength_MPa":      {"min": 900,  "max": 1620, "source": "ASM Handbook Vol 1"},
            "fracture_toughness_MPa_sqrt_m": {"min": 40, "max": 90,  "source": "ASM Handbook Vol 1"},
            "elongation":                 {"min": 0.08, "max": 0.16, "source": "ASM Handbook Vol 1"},
            "melting_point_C":            {"min": 1427, "max": 1510, "source": "ASM Handbook Vol 1"},
            "specific_heat_J_kgK":        {"min": 460,  "max": 480,  "source": "ASM Handbook Vol 1"},
            "thermal_conductivity_W_mK":  {"min": 38,   "max": 48,   "source": "ASM Handbook Vol 1"},
            "thermal_expansion_uK":       {"min": 12.3, "max": 13.0, "source": "ASM Handbook Vol 1"},
            "electrical_resistivity_uohm_cm": {"min": 22, "max": 26, "source": "ASM Handbook Vol 1"},
            "embodied_energy_MJ_kg":      {"min": 32,   "max": 38,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 2.4,  "max": 2.9,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.40, "max": 0.55, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 8,    "max": 12,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.6,  "max": 0.9,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Titanium ───────────────────────────────────────────────────────────
    {
        "id": "titanium-6al-4v",
        "name": "Titanium Ti-6Al-4V (Grade 5)",
        "family": "metals",
        "short_name": "Ti-6Al-4V",
        "subfamily": "titanium-alloys",
        "applications": ["Jet engine components", "Airframe structure", "Biomedical implants", "Racing components"],
        "notes": "Most widely used titanium alloy (~50% of all Ti production). Alpha-beta alloy. Annealed condition.",
        "properties": {
            "density_kg_m3":              {"min": 4420, "max": 4440, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 30,   "max": 60,   "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 113,  "max": 120,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 880,  "max": 1100, "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 950,  "max": 1170, "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 44, "max": 66,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.08, "max": 0.15, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 1604, "max": 1660, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 520,  "max": 530,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 6.7,  "max": 7.3,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 8.4,  "max": 8.8,  "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 170, "max": 180, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 500,  "max": 900,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 36,   "max": 55,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.50, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 40,   "max": 80,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 3.0,  "max": 5.5,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "titanium-grade-2",
        "name": "Titanium Grade 2 (commercially pure)",
        "family": "metals",
        "short_name": "Ti Grade 2",
        "subfamily": "titanium-alloys",
        "applications": ["Chemical processing vessels", "Heat exchangers", "Dental implants", "Architectural cladding"],
        "notes": "Most common CP-Ti grade. Excellent corrosion resistance. Lower strength than Ti-6Al-4V.",
        "properties": {
            "density_kg_m3":              {"min": 4500, "max": 4520, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 15,   "max": 35,   "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 103,  "max": 110,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 275,  "max": 345,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 345,  "max": 450,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 50, "max": 80,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.20, "max": 0.28, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 1665, "max": 1670, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 520,  "max": 530,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 16,   "max": 21,   "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 8.6,  "max": 8.9,  "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 56, "max": 62, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 500,  "max": 900,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 36,   "max": 55,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.50, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 40,   "max": 80,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 3.0,  "max": 5.5,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Copper alloys ──────────────────────────────────────────────────────
    {
        "id": "copper-c110",
        "name": "Copper C110 (ETP, electrolytic tough pitch)",
        "family": "metals",
        "short_name": "Copper C110",
        "subfamily": "copper-alloys",
        "applications": ["Electrical bus bars", "Wiring", "Heat exchangers", "Plumbing tube"],
        "notes": "99.9% pure Cu. Highest electrical and thermal conductivity of engineering metals.",
        "properties": {
            "density_kg_m3":              {"min": 8930, "max": 8950, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 8.0,  "max": 12.0, "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 117,  "max": 120,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 55,   "max": 220,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 220,  "max": 400,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 60, "max": 90,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.10, "max": 0.45, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 1083, "max": 1083, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 385,  "max": 390,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 388,  "max": 398,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 17.0, "max": 17.0, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 1.72, "max": 1.75, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 42,   "max": 70,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 2.4,  "max": 4.0,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.40, "max": 0.55, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 5,    "max": 10,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.3,  "max": 0.6,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "brass-c260",
        "name": "Brass C260 (cartridge brass, 70Cu-30Zn)",
        "family": "metals",
        "short_name": "Brass C260",
        "subfamily": "copper-alloys",
        "applications": ["Ammunition cartridges", "Musical instruments", "Hardware fittings", "Radiator cores"],
        "notes": "Most common single-phase brass. Excellent cold workability and corrosion resistance.",
        "properties": {
            "density_kg_m3":              {"min": 8520, "max": 8540, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 6.0,  "max": 10.0, "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 110,  "max": 115,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 75,   "max": 400,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 300,  "max": 530,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 30, "max": 50,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.05, "max": 0.50, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 915,  "max": 955,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 375,  "max": 380,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 120,  "max": 128,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 19.9, "max": 19.9, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 6.2, "max": 6.5, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 55,   "max": 85,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 3.3,  "max": 5.0,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.40, "max": 0.55, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 5,    "max": 12,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.3,  "max": 0.7,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "bronze-c932",
        "name": "Bronze C932 (SAE 660 bearing bronze)",
        "family": "metals",
        "short_name": "Bronze C932",
        "subfamily": "copper-alloys",
        "applications": ["Plain bearings", "Bushings", "Thrust washers", "Pump impellers"],
        "notes": "Cu-Sn-Pb bronze; low friction against steel. The standard bearing/bushing bronze.",
        "properties": {
            "density_kg_m3":              {"min": 8880, "max": 8960, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 8.0,  "max": 14.0, "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 103,  "max": 110,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 138,  "max": 193,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 240,  "max": 310,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 25, "max": 35,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.15, "max": 0.20, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 854,  "max": 1000, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 376,  "max": 385,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 72,   "max": 76,   "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 17.5, "max": 18.5, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 12, "max": 15, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 55,   "max": 85,   "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 3.3,  "max": 5.0,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.40, "max": 0.55, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 5,    "max": 12,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.3,  "max": 0.7,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "beryllium-copper",
        "name": "Beryllium copper C17200 (AT)",
        "family": "metals",
        "short_name": "BeCu C17200",
        "subfamily": "copper-alloys",
        "applications": ["Springs", "Electrical connectors", "Precision instruments", "Non-sparking tools"],
        "notes": "Highest-strength Cu alloy. AT (age tempered) condition. Beryllium dust is toxic — safety precautions required.",
        "properties": {
            "density_kg_m3":              {"min": 8250, "max": 8300, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 60,   "max": 140,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 128,  "max": 134,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 1100, "max": 1280, "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 1250, "max": 1400, "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 30, "max": 50,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.01, "max": 0.05, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 865,  "max": 980,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 418,  "max": 430,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 105,  "max": 115,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 17.0, "max": 17.8, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 6.8, "max": 7.5, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 250,  "max": 400,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 15,   "max": 25,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.35, "max": 0.50, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 20,   "max": 40,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.5,  "max": 3.0,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Nickel alloys ──────────────────────────────────────────────────────
    {
        "id": "inconel-625",
        "name": "Inconel 625 (nickel superalloy)",
        "family": "metals",
        "short_name": "Inconel 625",
        "subfamily": "nickel-alloys",
        "applications": ["Aerospace exhaust ducts", "Marine propellers", "Chemical processing", "Nuclear reactors"],
        "notes": "Ni-Cr-Mo alloy. Excellent corrosion and oxidation resistance to 980°C. Solid-solution strengthened.",
        "properties": {
            "density_kg_m3":              {"min": 8440, "max": 8450, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 40,   "max": 80,   "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 207,  "max": 215,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 414,  "max": 690,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 827,  "max": 1000, "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 70, "max": 110, "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.30, "max": 0.42, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 1290, "max": 1350, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 410,  "max": 430,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 9.8,  "max": 10.8, "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 12.8, "max": 13.0, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 128, "max": 132, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 180,  "max": 260,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 13,   "max": 20,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 15,   "max": 30,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.0,  "max": 2.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "inconel-718",
        "name": "Inconel 718 (nickel superalloy)",
        "family": "metals",
        "short_name": "Inconel 718",
        "subfamily": "nickel-alloys",
        "applications": ["Jet engine turbine discs", "Rocket motor casings", "Nuclear fuel spacers", "Cryogenic tankage"],
        "notes": "Ni-Fe-Cr alloy, precipitation hardened. Workhorse of high-temperature gas turbines.",
        "properties": {
            "density_kg_m3":              {"min": 8190, "max": 8220, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 40,   "max": 90,   "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 200,  "max": 211,  "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 1000, "max": 1185, "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 1240, "max": 1380, "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 50, "max": 90,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.12, "max": 0.18, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 1260, "max": 1336, "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 430,  "max": 440,  "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 11.4, "max": 11.8, "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 13.0, "max": 13.2, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 120, "max": 130, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 180,  "max": 270,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 13,   "max": 21,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 15,   "max": 30,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.0,  "max": 2.0,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Magnesium alloys ───────────────────────────────────────────────────
    {
        "id": "magnesium-az31b",
        "name": "Magnesium AZ31B (wrought)",
        "family": "metals",
        "short_name": "Mg AZ31B",
        "subfamily": "magnesium-alloys",
        "applications": ["Laptop casings", "Camera bodies", "Aerospace panels", "Automotive instrument panels"],
        "notes": "Most common wrought Mg alloy. H24 condition (strain hardened + partially annealed).",
        "properties": {
            "density_kg_m3":              {"min": 1770, "max": 1780, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 4.5,  "max": 6.5,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 44,   "max": 46,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 180,  "max": 220,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 240,  "max": 290,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 15, "max": 25,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.12, "max": 0.18, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 605,  "max": 630,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1000, "max": 1050, "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 96,   "max": 100,  "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 26.0, "max": 26.8, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 9.2, "max": 9.5, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 170,  "max": 250,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 10,   "max": 16,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 15,   "max": 25,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.0,  "max": 1.8,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "magnesium-az91d",
        "name": "Magnesium AZ91D (die cast)",
        "family": "metals",
        "short_name": "Mg AZ91D",
        "subfamily": "magnesium-alloys",
        "applications": ["Automotive gearbox housings", "Power tool cases", "Steering wheel frames"],
        "notes": "Most common Mg die-casting alloy. T4 treated. Very good castability.",
        "properties": {
            "density_kg_m3":              {"min": 1810, "max": 1820, "source": "ASM Handbook Vol 2"},
            "price_USD_kg":               {"min": 3.5,  "max": 5.5,  "source": "ASM Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 44,   "max": 47,   "source": "ASM Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 150,  "max": 200,  "source": "ASM Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 230,  "max": 290,  "source": "ASM Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 13, "max": 22,  "source": "ASM Handbook Vol 2"},
            "elongation":                 {"min": 0.03, "max": 0.07, "source": "ASM Handbook Vol 2"},
            "melting_point_C":            {"min": 468,  "max": 598,  "source": "ASM Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1000, "max": 1050, "source": "ASM Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 72,   "max": 80,   "source": "ASM Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 26.0, "max": 27.0, "source": "ASM Handbook Vol 2"},
            "electrical_resistivity_uohm_cm": {"min": 17, "max": 19, "source": "ASM Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 170,  "max": 250,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 10,   "max": 16,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.30, "max": 0.45, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 15,   "max": 25,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.0,  "max": 1.8,  "source": "Bath ICE v3.0"},
        }
    },

    # ── Technical ceramics ─────────────────────────────────────────────────
    {
        "id": "zirconia-y-tzp",
        "name": "Zirconia, Y-TZP (yttria-stabilized tetragonal)",
        "family": "ceramics-technical",
        "short_name": "Zirconia Y-TZP",
        "subfamily": "oxide-ceramics",
        "applications": ["Dental crowns", "Fuel cell electrolytes", "Hip-joint heads", "Oxygen sensors"],
        "notes": "Transformation-toughened zirconia — highest fracture toughness of oxide ceramics (8–12 MPa√m).",
        "properties": {
            "density_kg_m3":              {"min": 5600, "max": 6100, "source": "ASM Engineered Materials Handbook Vol 4"},
            "price_USD_kg":               {"min": 40,   "max": 120,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "youngs_modulus_GPa":         {"min": 190,  "max": 210,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "yield_strength_MPa":         {"min": 900,  "max": 1200, "source": "ASM Engineered Materials Handbook Vol 4"},
            "fracture_toughness_MPa_sqrt_m": {"min": 8, "max": 12,   "source": "ASM Engineered Materials Handbook Vol 4"},
            "melting_point_C":            {"min": 2715, "max": 2715, "source": "ASM Engineered Materials Handbook Vol 4"},
            "specific_heat_J_kgK":        {"min": 450,  "max": 470,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_conductivity_W_mK":  {"min": 2.0,  "max": 2.5,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_expansion_uK":       {"min": 10.0, "max": 11.0, "source": "ASM Engineered Materials Handbook Vol 4"},
            "embodied_energy_MJ_kg":      {"min": 200,  "max": 350,  "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 12,   "max": 22,   "source": "Bath ICE v3.0 (estimate)"},
        }
    },
    {
        "id": "silicon-nitride",
        "name": "Silicon nitride (Si₃N₄, RBSN/HPSN)",
        "family": "ceramics-technical",
        "short_name": "Si₃N₄",
        "subfamily": "nitride-ceramics",
        "applications": ["Cutting tool inserts", "Bearing balls", "Turbocharger rotors", "Diesel engine parts"],
        "notes": "Best combination of strength and toughness of engineering ceramics. HPSN (hot-pressed) at high end.",
        "properties": {
            "density_kg_m3":              {"min": 3100, "max": 3300, "source": "ASM Engineered Materials Handbook Vol 4"},
            "price_USD_kg":               {"min": 20,   "max": 80,   "source": "ASM Engineered Materials Handbook Vol 4"},
            "youngs_modulus_GPa":         {"min": 290,  "max": 320,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "yield_strength_MPa":         {"min": 650,  "max": 1000, "source": "ASM Engineered Materials Handbook Vol 4"},
            "fracture_toughness_MPa_sqrt_m": {"min": 5, "max": 7,    "source": "ASM Engineered Materials Handbook Vol 4"},
            "melting_point_C":            {"min": 1850, "max": 1900, "source": "ASM Engineered Materials Handbook Vol 4"},
            "specific_heat_J_kgK":        {"min": 680,  "max": 720,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_conductivity_W_mK":  {"min": 15,   "max": 43,   "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_expansion_uK":       {"min": 3.0,  "max": 3.6,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "embodied_energy_MJ_kg":      {"min": 150,  "max": 280,  "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 9,    "max": 18,   "source": "Bath ICE v3.0 (estimate)"},
        }
    },
    {
        "id": "boron-carbide",
        "name": "Boron carbide (B₄C)",
        "family": "ceramics-technical",
        "short_name": "B₄C",
        "subfamily": "carbide-ceramics",
        "applications": ["Ballistic armor (lightest)", "Abrasive blasting nozzles", "Nuclear control rods", "Sandblast equipment"],
        "notes": "3rd hardest material after diamond and CBN. Lightest hard ceramic.",
        "properties": {
            "density_kg_m3":              {"min": 2490, "max": 2520, "source": "ASM Engineered Materials Handbook Vol 4"},
            "price_USD_kg":               {"min": 40,   "max": 200,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "youngs_modulus_GPa":         {"min": 440,  "max": 470,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "yield_strength_MPa":         {"min": 300,  "max": 500,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "fracture_toughness_MPa_sqrt_m": {"min": 2.5, "max": 3.5, "source": "ASM Engineered Materials Handbook Vol 4"},
            "melting_point_C":            {"min": 2450, "max": 2450, "source": "ASM Engineered Materials Handbook Vol 4"},
            "specific_heat_J_kgK":        {"min": 950,  "max": 1000, "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_conductivity_W_mK":  {"min": 30,   "max": 35,   "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_expansion_uK":       {"min": 5.0,  "max": 6.0,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "embodied_energy_MJ_kg":      {"min": 400,  "max": 800,  "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 25,   "max": 50,   "source": "Bath ICE v3.0 (estimate)"},
        }
    },
    {
        "id": "hydroxyapatite",
        "name": "Hydroxyapatite (HA), dense sintered",
        "family": "ceramics-technical",
        "short_name": "Hydroxyapatite",
        "subfamily": "bioceramic",
        "applications": ["Bone scaffold implants", "Dental root fillings", "Orthopaedic coatings", "Drug delivery carriers"],
        "notes": "Main mineral of bone. Bioactive, osteoconductive. Brittle — not for load-bearing alone.",
        "properties": {
            "density_kg_m3":              {"min": 3100, "max": 3220, "source": "ASM Engineered Materials Handbook Vol 4"},
            "price_USD_kg":               {"min": 100,  "max": 500,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "youngs_modulus_GPa":         {"min": 70,   "max": 120,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "yield_strength_MPa":         {"min": 40,   "max": 200,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "fracture_toughness_MPa_sqrt_m": {"min": 0.6, "max": 1.3, "source": "ASM Engineered Materials Handbook Vol 4"},
            "melting_point_C":            {"min": 1614, "max": 1614, "source": "ASM Engineered Materials Handbook Vol 4"},
            "specific_heat_J_kgK":        {"min": 750,  "max": 800,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_conductivity_W_mK":  {"min": 1.2,  "max": 2.3,  "source": "ASM Engineered Materials Handbook Vol 4"},
            "thermal_expansion_uK":       {"min": 11.0, "max": 14.0, "source": "ASM Engineered Materials Handbook Vol 4"},
        }
    },

    # ── Composites ─────────────────────────────────────────────────────────
    {
        "id": "cfrp-ud",
        "name": "CFRP, unidirectional (60% Vf, T300/epoxy)",
        "family": "composites",
        "short_name": "CFRP UD",
        "subfamily": "carbon-fiber-composites",
        "applications": ["Aerospace spars", "Formula 1 monocoques", "Bicycle frames", "Wind turbine blades"],
        "notes": "Fiber-direction (0°) properties. T300 carbon fiber, 60% Vf. Transverse properties ~10× lower.",
        "properties": {
            "density_kg_m3":              {"min": 1550, "max": 1600, "source": "Ashby App A (6th ed., 2025)"},
            "price_USD_kg":               {"min": 25,   "max": 80,   "source": "Ashby App A (6th ed., 2025)"},
            "youngs_modulus_GPa":         {"min": 120,  "max": 145,  "source": "Ashby App A (6th ed., 2025)"},
            "yield_strength_MPa":         {"min": 1000, "max": 1600, "source": "Ashby App A (6th ed., 2025)"},
            "ultimate_strength_MPa":      {"min": 1000, "max": 1600, "source": "Ashby App A (6th ed., 2025)"},
            "fracture_toughness_MPa_sqrt_m": {"min": 25, "max": 45,  "source": "Ashby App A (6th ed., 2025)"},
            "elongation":                 {"min": 0.006, "max": 0.015, "source": "Ashby App A (6th ed., 2025)"},
            "specific_heat_J_kgK":        {"min": 900,  "max": 1100, "source": "Ashby App A (6th ed., 2025)"},
            "thermal_conductivity_W_mK":  {"min": 2.0,  "max": 10.0, "source": "Ashby App A (6th ed., 2025)"},
            "thermal_expansion_uK":       {"min": -0.5, "max": 2.0,  "source": "Ashby App A (6th ed., 2025)"},
            "embodied_energy_MJ_kg":      {"min": 230,  "max": 450,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 14,   "max": 28,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.05, "max": 0.20, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 20,   "max": 50,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 1.5,  "max": 4.0,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "aramid-composite",
        "name": "Aramid/Kevlar composite (60% Vf, Kevlar 49/epoxy)",
        "family": "composites",
        "short_name": "Kevlar composite",
        "subfamily": "aramid-fiber-composites",
        "applications": ["Ballistic vests", "Helmets", "Pressure vessels", "Marine hulls"],
        "notes": "Fiber-direction tensile properties. Poor in compression (fibers buckle). Excellent specific strength.",
        "properties": {
            "density_kg_m3":              {"min": 1300, "max": 1380, "source": "Ashby App A (6th ed., 2025)"},
            "price_USD_kg":               {"min": 25,   "max": 60,   "source": "Ashby App A (6th ed., 2025)"},
            "youngs_modulus_GPa":         {"min": 70,   "max": 85,   "source": "Ashby App A (6th ed., 2025)"},
            "yield_strength_MPa":         {"min": 1200, "max": 1450, "source": "Ashby App A (6th ed., 2025)"},
            "ultimate_strength_MPa":      {"min": 1400, "max": 1800, "source": "Ashby App A (6th ed., 2025)"},
            "fracture_toughness_MPa_sqrt_m": {"min": 5, "max": 15,   "source": "Ashby App A (6th ed., 2025)"},
            "elongation":                 {"min": 0.015, "max": 0.028, "source": "Ashby App A (6th ed., 2025)"},
            "specific_heat_J_kgK":        {"min": 1100, "max": 1300, "source": "Ashby App A (6th ed., 2025)"},
            "thermal_conductivity_W_mK":  {"min": 0.04, "max": 0.16, "source": "Ashby App A (6th ed., 2025)"},
            "thermal_expansion_uK":       {"min": -2.0, "max": 2.0,  "source": "Ashby App A (6th ed., 2025)"},
            "embodied_energy_MJ_kg":      {"min": 150,  "max": 250,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 9,    "max": 16,   "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.02, "max": 0.10, "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "basalt-fiber-composite",
        "name": "Basalt fiber composite (55% Vf, UD/epoxy)",
        "family": "composites",
        "short_name": "Basalt composite",
        "subfamily": "mineral-fiber-composites",
        "applications": ["Rebar in concrete", "Wind turbine blades", "Pipe linings", "Automotive body panels"],
        "notes": "Lower cost than CFRP; better temperature resistance than GFRP. Sustainable — made from volcanic rock.",
        "properties": {
            "density_kg_m3":              {"min": 1900, "max": 2100, "source": "Fibre Glast / published literature"},
            "price_USD_kg":               {"min": 8,    "max": 20,   "source": "Fibre Glast / published literature"},
            "youngs_modulus_GPa":         {"min": 55,   "max": 75,   "source": "Fibre Glast / published literature"},
            "yield_strength_MPa":         {"min": 800,  "max": 1150, "source": "Fibre Glast / published literature"},
            "ultimate_strength_MPa":      {"min": 900,  "max": 1200, "source": "Fibre Glast / published literature"},
            "fracture_toughness_MPa_sqrt_m": {"min": 20, "max": 35,  "source": "Fibre Glast / published literature"},
            "elongation":                 {"min": 0.015, "max": 0.025, "source": "Fibre Glast / published literature"},
            "specific_heat_J_kgK":        {"min": 850,  "max": 1000, "source": "Fibre Glast / published literature"},
            "thermal_conductivity_W_mK":  {"min": 0.5,  "max": 1.5,  "source": "Fibre Glast / published literature"},
            "thermal_expansion_uK":       {"min": 6.0,  "max": 9.0,  "source": "Fibre Glast / published literature"},
            "embodied_energy_MJ_kg":      {"min": 15,   "max": 35,   "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 1.0,  "max": 2.5,  "source": "Bath ICE v3.0 (estimate)"},
        }
    },

    # ── Engineering polymers ───────────────────────────────────────────────
    {
        "id": "uhmwpe",
        "name": "UHMWPE (ultra-high molecular weight polyethylene)",
        "family": "polymers",
        "short_name": "UHMWPE",
        "subfamily": "thermoplastics",
        "applications": ["Hip and knee implant liners", "Cutting boards", "Conveyor wear strips", "Ballistic armor panels"],
        "notes": "MW > 3.5 million g/mol. Outstanding wear and impact resistance; low friction.",
        "properties": {
            "density_kg_m3":              {"min": 930,  "max": 940,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 4.0,  "max": 8.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 0.7,  "max": 1.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 20,   "max": 30,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 30,   "max": 45,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 2.5, "max": 5.5, "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 2.0,  "max": 4.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "melting_point_C":            {"min": 130,  "max": 145,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1800, "max": 2100, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.42, "max": 0.51, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 130,  "max": 180,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 80,   "max": 100,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 2.3,  "max": 3.2,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.10, "max": 0.25, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 10,   "max": 18,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.7,  "max": 1.2,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "polyamide-66",
        "name": "Polyamide 6/6 (Nylon 66, PA66)",
        "family": "polymers",
        "short_name": "Nylon 66",
        "subfamily": "thermoplastics",
        "applications": ["Gears and bearings", "Zip ties", "Electrical connectors", "Toothbrush bristles"],
        "notes": "Higher melting point (255–265°C) and modulus than PA6. Moisture absorbs → properties change.",
        "properties": {
            "density_kg_m3":              {"min": 1130, "max": 1150, "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 3.5,  "max": 6.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 2.0,  "max": 3.5,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 55,   "max": 85,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 75,   "max": 95,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 2.5, "max": 4.0, "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 0.15, "max": 0.60, "source": "ASM Engineered Materials Handbook Vol 2"},
            "melting_point_C":            {"min": 255,  "max": 265,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "glass_temperature_C":        {"min": 47,   "max": 80,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1600, "max": 1700, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.24, "max": 0.27, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 80,   "max": 100,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 138,  "max": 160,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 6.1,  "max": 8.0,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.10, "max": 0.25, "source": "Bath ICE v3.0"},
            "recycle_energy_MJ_kg":       {"min": 12,   "max": 20,   "source": "Bath ICE v3.0"},
            "recycle_co2_kg_kg":          {"min": 0.8,  "max": 1.4,  "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "polysulfone",
        "name": "Polysulfone (PSU)",
        "family": "polymers",
        "short_name": "Polysulfone",
        "subfamily": "thermoplastics",
        "applications": ["Medical sterilisable components", "Membrane housings", "Circuit boards", "Plumbing fittings"],
        "notes": "Amorphous high-performance thermoplastic. Tg ~185°C; autoclave sterilisable.",
        "properties": {
            "density_kg_m3":              {"min": 1240, "max": 1250, "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 12,   "max": 20,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 2.5,  "max": 2.7,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 55,   "max": 70,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 70,   "max": 80,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 1.5, "max": 2.2, "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 0.10, "max": 0.25, "source": "ASM Engineered Materials Handbook Vol 2"},
            "glass_temperature_C":        {"min": 185,  "max": 190,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1300, "max": 1400, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.26, "max": 0.28, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 55,   "max": 60,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 95,   "max": 130,  "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 5.5,  "max": 8.0,  "source": "Bath ICE v3.0 (estimate)"},
        }
    },
    {
        "id": "polyimide",
        "name": "Polyimide (PI, Kapton-type)",
        "family": "polymers",
        "short_name": "Polyimide",
        "subfamily": "thermoplastics",
        "applications": ["Flexible printed circuit substrates", "High-temperature insulation", "Jet engine wire wrap", "Space blankets"],
        "notes": "No melting point (decomposes ~500°C). Continuous service to ~260°C. Excellent dielectric.",
        "properties": {
            "density_kg_m3":              {"min": 1410, "max": 1430, "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 80,   "max": 200,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 2.5,  "max": 3.1,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 80,   "max": 120,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 90,   "max": 140,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 1.0, "max": 1.8, "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 0.03, "max": 0.08, "source": "ASM Engineered Materials Handbook Vol 2"},
            "glass_temperature_C":        {"min": 360,  "max": 410,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1090, "max": 1130, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.10, "max": 0.35, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 20,   "max": 30,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "dielectric_constant":        {"min": 3.4,  "max": 3.6,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 200,  "max": 350,  "source": "Bath ICE v3.0 (estimate)"},
            "co2_footprint_kg_kg":        {"min": 12,   "max": 22,   "source": "Bath ICE v3.0 (estimate)"},
        }
    },
    {
        "id": "tpu",
        "name": "Thermoplastic polyurethane (TPU)",
        "family": "polymers",
        "short_name": "TPU",
        "subfamily": "thermoplastics",
        "applications": ["Shoe soles", "Hose and tubing", "Cable jacketing", "Phone cases", "Wheels and rollers"],
        "notes": "Bridges gap between rubber and plastic. Excellent abrasion resistance and flex fatigue life.",
        "properties": {
            "density_kg_m3":              {"min": 1110, "max": 1250, "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 3.5,  "max": 7.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 0.004,"max": 0.06, "source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 10,   "max": 60,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 25,   "max": 65,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "fracture_toughness_MPa_sqrt_m": {"min": 3.0, "max": 8.0, "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 3.0,  "max": 8.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "melting_point_C":            {"min": 150,  "max": 220,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "glass_temperature_C":        {"min": -60,  "max": -20,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1500, "max": 1800, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.17, "max": 0.25, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 100,  "max": 200,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 80,   "max": 110,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 4.5,  "max": 6.5,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.05, "max": 0.20, "source": "Bath ICE v3.0"},
        }
    },

    # ── Elastomers ─────────────────────────────────────────────────────────
    {
        "id": "epdm-rubber",
        "name": "EPDM rubber (ethylene propylene diene)",
        "family": "elastomers",
        "short_name": "EPDM",
        "subfamily": "synthetic-rubber",
        "applications": ["Automotive door seals", "Roofing membranes", "Radiator hoses", "Window gaskets", "Outdoor seals"],
        "notes": "Excellent UV, ozone and weather resistance. Operating range −50 to +150°C.",
        "properties": {
            "density_kg_m3":              {"min": 860,  "max": 880,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "price_USD_kg":               {"min": 2.0,  "max": 4.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "youngs_modulus_GPa":         {"min": 0.003,"max": 0.010,"source": "ASM Engineered Materials Handbook Vol 2"},
            "yield_strength_MPa":         {"min": 7,    "max": 18,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "ultimate_strength_MPa":      {"min": 10,   "max": 22,   "source": "ASM Engineered Materials Handbook Vol 2"},
            "elongation":                 {"min": 2.0,  "max": 6.0,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "glass_temperature_C":        {"min": -60,  "max": -50,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "specific_heat_J_kgK":        {"min": 1900, "max": 2100, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_conductivity_W_mK":  {"min": 0.25, "max": 0.40, "source": "ASM Engineered Materials Handbook Vol 2"},
            "thermal_expansion_uK":       {"min": 160,  "max": 220,  "source": "ASM Engineered Materials Handbook Vol 2"},
            "embodied_energy_MJ_kg":      {"min": 70,   "max": 100,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": 3.5,  "max": 5.0,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.05, "max": 0.15, "source": "Bath ICE v3.0"},
        }
    },

    # ── Natural / bio-based ────────────────────────────────────────────────
    {
        "id": "bamboo",
        "name": "Bamboo (Moso, along grain)",
        "family": "natural",
        "short_name": "Bamboo",
        "subfamily": "natural-plant",
        "applications": ["Structural building material", "Flooring", "Bicycle frames", "Furniture", "Scaffolding"],
        "notes": "Along-grain (longitudinal) properties. Tensile strength rivals mild steel at 1/8 the density.",
        "properties": {
            "density_kg_m3":              {"min": 600,  "max": 900,  "source": "Cambridge Materials Data Book (2011)"},
            "price_USD_kg":               {"min": 0.5,  "max": 2.0,  "source": "Cambridge Materials Data Book (2011)"},
            "youngs_modulus_GPa":         {"min": 10,   "max": 20,   "source": "Cambridge Materials Data Book (2011)"},
            "yield_strength_MPa":         {"min": 100,  "max": 280,  "source": "Cambridge Materials Data Book (2011)"},
            "ultimate_strength_MPa":      {"min": 120,  "max": 300,  "source": "Cambridge Materials Data Book (2011)"},
            "fracture_toughness_MPa_sqrt_m": {"min": 3, "max": 7,    "source": "Cambridge Materials Data Book (2011)"},
            "elongation":                 {"min": 0.01, "max": 0.03, "source": "Cambridge Materials Data Book (2011)"},
            "specific_heat_J_kgK":        {"min": 1300, "max": 1500, "source": "Cambridge Materials Data Book (2011)"},
            "thermal_conductivity_W_mK":  {"min": 0.10, "max": 0.20, "source": "Cambridge Materials Data Book (2011)"},
            "thermal_expansion_uK":       {"min": 3.0,  "max": 6.0,  "source": "Cambridge Materials Data Book (2011)"},
            "embodied_energy_MJ_kg":      {"min": 0.5,  "max": 5.0,  "source": "Bath ICE v3.0"},
            "co2_footprint_kg_kg":        {"min": -1.5, "max": 0.5,  "source": "Bath ICE v3.0"},
            "recycle_fraction":           {"min": 0.50, "max": 0.90, "source": "Bath ICE v3.0"},
        }
    },
    {
        "id": "bone-cortical",
        "name": "Bone, cortical (human femur)",
        "family": "natural",
        "short_name": "Cortical bone",
        "subfamily": "natural-bio",
        "applications": ["Biomedical reference material", "Scaffold design target", "Orthopaedic implant benchmarking"],
        "notes": "Properties along the longitudinal axis. Wide range reflects age/anatomical variation.",
        "properties": {
            "density_kg_m3":              {"min": 1700, "max": 2000, "source": "Cambridge Materials Data Book (2011)"},
            "youngs_modulus_GPa":         {"min": 7,    "max": 25,   "source": "Cambridge Materials Data Book (2011)"},
            "yield_strength_MPa":         {"min": 100,  "max": 200,  "source": "Cambridge Materials Data Book (2011)"},
            "ultimate_strength_MPa":      {"min": 120,  "max": 230,  "source": "Cambridge Materials Data Book (2011)"},
            "fracture_toughness_MPa_sqrt_m": {"min": 2.5, "max": 7.0, "source": "Cambridge Materials Data Book (2011)"},
            "elongation":                 {"min": 0.01, "max": 0.03, "source": "Cambridge Materials Data Book (2011)"},
            "specific_heat_J_kgK":        {"min": 1100, "max": 1300, "source": "Cambridge Materials Data Book (2011)"},
            "thermal_conductivity_W_mK":  {"min": 0.4,  "max": 0.8,  "source": "Cambridge Materials Data Book (2011)"},
        }
    },
]


def rebuild_materials_json():
    """Merge all individual material JSONs into the flat materials.json."""
    all_materials = []
    for p in sorted(MAT_DIR.glob("*.json")):
        with open(p) as f:
            all_materials.append(json.load(f))
    doc = {
        "count": len(all_materials),
        "source": "Ashby App A (6th ed., 2025) + ASM Handbooks + Bath ICE v3.0",
        "materials": all_materials,
    }
    with open(DATA_DIR / "materials.json", "w") as f:
        json.dump(doc, f, indent=2)
    print(f"Rebuilt materials.json — {len(all_materials)} materials total.")


def main():
    existing_ids = {p.stem for p in MAT_DIR.glob("*.json")}
    added, skipped = 0, 0
    for mat in NEW_MATERIALS:
        mid = mat["id"]
        if mid in existing_ids:
            print(f"  SKIP (exists): {mid}")
            skipped += 1
            continue
        path = MAT_DIR / f"{mid}.json"
        with open(path, "w") as f:
            json.dump(mat, f, indent=2)
        print(f"  ADD: {mid}")
        added += 1

    print(f"\nAdded {added} new materials, skipped {skipped} existing.")
    rebuild_materials_json()


if __name__ == "__main__":
    main()
